production:
    email_delivery:
        delivery_method: :smtp
        smtp_settings:
            address: smtp7.byd.com
            port: 25
            domain: bydhq.com.cn
            authentication: :login
            user_name: liang.qiang1@byd.com
            password: lq200069

